package com.example.myaiassistant.knowledge.deep

import com.example.myaiassistant.knowledge.AurixDeepKnowledgeItem
import com.example.myaiassistant.knowledge.ConfidenceLevel

object AurixAviationKnowledge {
    val entries = listOf(
        AurixDeepKnowledgeItem("Aviation", "Lift", listOf("aircraft lift"), """Lift is an aerodynamic force component generated by airflow around an aircraft and directed perpendicular to the relative wind.""", ConfidenceLevel.HIGH, false),
        AurixDeepKnowledgeItem("Aviation", "Drag", listOf("aircraft drag"), """Drag is the aerodynamic force opposing relative motion through air.""", ConfidenceLevel.HIGH, false),
        AurixDeepKnowledgeItem("Aviation", "Thrust", listOf("aircraft thrust"), """Thrust is propulsion-generated force contributing to aircraft forward acceleration.""", ConfidenceLevel.HIGH, false),
        AurixDeepKnowledgeItem("Aviation", "Turbofan", listOf("turbofan engine"), """A turbofan combines a core engine with fan-generated airflow and is widely used in modern passenger aircraft.""", ConfidenceLevel.HIGH, false),
        AurixDeepKnowledgeItem("Aviation", "Helicopter", listOf("helicopter"), """A helicopter is a rotary-wing aircraft capable of hover and controlled flight using rotor aerodynamics.""", ConfidenceLevel.HIGH, false),
        AurixDeepKnowledgeItem("Aviation", "Altitude", listOf("aviation altitude"), """Altitude is vertical distance from a specified reference level or datum.""", ConfidenceLevel.HIGH, false),
        AurixDeepKnowledgeItem("Aviation", "Runway", listOf("runway airport"), """A runway is a prepared surface or area for aircraft takeoff and landing.""", ConfidenceLevel.HIGH, false),
        AurixDeepKnowledgeItem("Aviation", "Air Traffic Control", listOf("air traffic control atc"), """ATC services support safe, orderly and efficient aircraft movement and separation.""", ConfidenceLevel.HIGH, false),
    )
}
